---
name: "Benchmark run (OpenRouter)"
description: "Request a benchmark run for an OpenRouter model"
title: "Benchmark: <author>/<model> (OpenRouter)"
body:
  - type: markdown
    attributes:
      value: |
        <table border="0" cellspacing="0" cellpadding="0" style="background: transparent;">
        <tr>
        <td valign="middle">
        You can find the model slug in the <a href="https://openrouter.ai/models" target="_blank">OpenRouter site</a> and use the 📋 button to copy the model slug.
        </td>
        <td width="60%">
        <img src="https://raw.githubusercontent.com/victorigualada/openrouter-benchmarks/main/.github/assets/copy-model-slug.png" alt="Copy model slug" width="100%">
        </td>
        </tr>
        </table>
        
        - The benchmark will run when the `run-benchmark` label is applied by a maintainer.

  - type: input
    id: model
    attributes:
      label: Model slug (OpenRouter)
      description: |
        Required format: \<author\>/\<model\>
      placeholder: mistralai/mistral-large-2512
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: Any context for reviewers / maintainers.
    validations:
      required: false
